### ISSUE TITLE
Encoding 0 bytes behavior

### ISSUE THREAD

**Issue by shou1dwe** [kafka4beam/kafka_protocol#78]
according to the kafka protocol doc: https://kafka.apache.org/protocol#protocol_types
"bytes" should be encoded as:

> Represents a raw sequence of bytes. First the length N is given as an INT32. Then N bytes follow.

But I can see that there is a special case in the library where it encode 0 bytes as `<<-1:32/signed-integer>>` [(Ref)](https://github.com/klarna/kafka_protocol/blob/master/src/kpro_lib.erl#L150), but not `[<<0:32>>, <<>>]` as what the doc says.

I am seeing the kafka broker rejecting a `sasl_authenticate` v0 request call with `auth_bytes` having 0 bytes content.

Is the special 0 bytes encoding behavior intended for some other case?

**Comment by mikpe** [comment]
@zmstone do you know if this is deliberate, and if so why?

**Comment by zmstone** [comment]
I'd like to know the versions, `kafka_protocol` version ? Kafka version ?

In general In Kafka protocol `-1` means `NULL` and `0` means empty.
However Kafka server has been quite tolerable with `NULL` and empty in many cases.

It's quite long ago, so I can't remember if the special case for empty as `NULL` was
to keep backward compatibility for encoding behaviour, or
if it was due to a bug in early version Kafka servers which had trouble processing empty bytes.
The later is more likely the case, it has always been quite unclear until `nullable_string` was introduced,
However AFAIK there is no `nullable_bytes` type in the schema.

Why does your code send `<<>>` for `auth_bytes` ? 
If the bytes are constructed by `kpro_sasl` module, it seems impossible to be empty.

**Comment by shou1dwe** [comment]
sorry for the late reply. Kafka_protocol 2.4.0 and Kafka at that time was 1.1.0. I haven't tried this on the newer Kafka cluster (2.6.0) we have.

We are using kerberos with sasl_auth Erlang module, which I believe underlying is [Cyrus SASL](https://www.cyrusimap.org/sasl/sasl/developer/programming.html). I am by no means an expert in SASL, but I notice that in one of the interaction step there is an <<>> generated to be sent to server side. In the old days without Kafka Protocol envelop, this is just encoded as bytes length = 0 with no subsequent data.

**Comment by vikas15bhardwaj** [comment]
We have faced the same issue with Kerberos Auth due to the Encoding. When we changed the `encode(bytes, B)` method as mentioned above, It started working. Cyrus SASL returns 0 bytes token which needs to be sent to Kafka to complete the auth. Without this step Kerberos auth does not work. Can you look into this, It will be a big help if you can update the library with a fix. Let me know if you need any more details around it.

**Comment by zmstone** [comment]
sorry for the late reply.
I'll run some regression tests with different Kafka versions see of they can cope with 0.
If yes, I'll fix it in the latest version.

Let us know if you need to port it back to older versions.

**Comment by vikas15bhardwaj** [comment]
@zmstone Did you get a chance to look into this issue?

**Comment by zmstone** [comment]
sorry. I totally forgot about this issue.
Will pick it up this week
